---
pulsar_systemd: true
pulsar_systemd_runner: webless

pulsar_root: /opt/pulsar
pulsar_server_dir: "{{ pulsar_root }}/server"
pulsar_venv_dir: "{{ pulsar_root }}/venv"

pulsar_optional_dependencies:
  - requests
  - requests-toolbelt

pulsar_yaml_config:
  message_queue_url: "http://<relay-host>:9000"
  message_queue_username: admin
  message_queue_password: password
