gravity:
  gunicorn:
    enable: true
    bind: 0.0.0.0:8080
  celery:
  handlers:
    handler:
      processes: 2
      pools:
        - job-handlers
  gx_it_proxy:
  tusd:
  reports:
galaxy:
  admin_users: dima@local.hpc
  galaxy_infrastructure_url: http://192.168.2.1:8080
  job_config_file: config/job_conf.yml
  default_job_external_setup: true
  container_resolvers_config_file: /home/ubuntu/galaxy/config/container_resolvers.yml
